
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    volumes:
      - ./heimdall/config:/config
    ports:
      - 80:80
    networks:
      - homeassistant
    restart: unless-stopped

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./config:/config
    environment:
      - TZ=Asia/Dubai
    restart: unless-stopped
    privileged: true
    network_mode: host          # NECESARIO para Matter
    depends_on:
      - mosquitto
      - zigbee2mqtt
      - nodered

  matter-server:
    container_name: matter-server
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    network_mode: host          # NECESARIO para mDNS / Thread / Matter
    restart: unless-stopped
    volumes:
      - ./matter:/data

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - homeassistant

  nodered:
    container_name: nodered
    image: nodered/node-red:latest
    restart: unless-stopped
    volumes:
      - ./node-red/data:/data
    ports:
      - "1880:1880"
    networks:
      - homeassistant
    environment:
      - TZ=Asia/Dubai
      - NODE_OPTIONS=--max_old_space_size=4096

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    restart: unless-stopped
    volumes:
      - ./zigbee2mqtt/data:/app/data
    ports:
      - "8080:8080"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    networks:
      - homeassistant
    environment:
      - TZ=Asia/Dubai
    depends_on:
      - mosquitto

networks:
  homeassistant:
    driver: bridge
